[package]
name = "gyazo"
version = "0.1.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]
edition = "2021"

[dependencies]
futures = "0.3"
aws-config = "0.9"
aws-sdk-s3 = "0.9"
rust-crypto = "0.2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs"] }
