[package]
name = "pfs-unpack"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
byteorder = "1"
env_logger = "0.10"
log = "0.4"
ring = "0.16"
