[package]
name = "grpc-sample"
version = "0.1.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]
edition = "2021"

[build-dependencies]
tonic-build = { version = "0.8" }

[dependencies]
tonic = "0.8"
prost = "0.11"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
