[package]
name = "grpc-sample"
version = "0.1.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]
edition = "2021"

[build-dependencies]
tonic-build = { version = "0.7" }

[dependencies]
tonic = "0.7"
prost = "0.10"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
