#!/bin/sh

dev=$1
power=$2

for i in $(seq 10)
do
  dbus-send --print-reply --system --type=method_call --dest=org.bluez \
    /org/bluez/$dev \
    org.freedesktop.DBus.Properties.Set \
    string:org.bluez.Adapter1 \
    string:Powered \
    variant:boolean:$power \
    && exit 0
  sleep 1
done
