version: '2'
services:
  web:
    extends:
      file: docker-compose.common.yml
      service: common
    build: .
    links:
      - db
      - redis
    ports:
      - 4000:4000
  worker:
    extends:
      file: docker-compose.common.yml
      service: common
    build: .
    environment:
      C_FORCE_ROOT: 1
    links:
      - db
      - redis
    command: sentry celery worker
  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: password
  redis:
    image: redis:3.0
