[package]
name = "tls-cert-expiration"
version = "0.1.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]
edition = "2021"

[dependencies]
chrono = "0.4"
rustls = "0.20"
rustls-native-certs = "0.6"
structopt = "0.3"
webpki = "0.22"
x509-parser = "0.12"
