[package]
name = "tls-cert-expiration"
version = "0.1.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
getopts = "0.2"
rustls = "0.18"
rustls-native-certs = "0.4"
webpki = "0.21"
x509-parser = "0.7"
