[package]
name = "tls-cert-expiration"
version = "0.1.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]
edition = "2021"

[dependencies]
chrono.workspace = true
clap.workspace = true
rustls = "0.21"
rustls-native-certs = "0.6"
x509-parser = "0.15"
