[package]
name = "tls-cert-expiration"
version = "0.1.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
failure = "0.1"
getopts = "0.2"
rustls = "0.17"
rustls-native-certs = "0.3"
webpki = "0.21"
x509-parser = "0.6"
