[package]
name = "errno"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen.workspace = true
once_cell = "1"
libc.workspace = true
