[package]
name = "s3-du"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config.workspace = true
aws-sdk-s3.workspace = true
clap.workspace = true
tokio.workspace = true
