[package]
name = "jrsonnet-lint"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jrsonnet-parser = "0.4"

[dev-dependencies]
indoc = "1"
