[package]
name = "jrsonnet-lint"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jrsonnet-parser.workspace = true

[dev-dependencies]
indoc = "2"
