[package]
name = "git-pkgbuild-commit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
gix = { version = "0.63", default-features = false, features = ["index"] }
