[package]
name = "agent-proto"
version = "0.1.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tonic-build = "0.4"

[dependencies]
anyhow = "1"
tempfile = "3"
tonic = "0.4"
prost = "0.7"
tokio = { version = "1.0", features = ["rt-multi-thread", "net", "signal"] }
async-stream = "0.3"
futures = "0.3"
tower = "0.4"
nix = "0.20"
log = "0.4"
env_logger = "0.8"
libc = "0.2"
