[package]
name = "rdig"
version = "0.1.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]
edition = "2021"

[dependencies]
anstream.workspace = true
anstyle.workspace = true
tokio.workspace = true
trust-dns-resolver = "0.22"
